validation to develop target

diff --git a/.github/workflows/pull-request.yml b/.github/workflows/pull-request.yml
--- a/.github/workflows/pull-request.yml
+++ b/.github/workflows/pull-request.yml
@@ -8,18 +8,39 @@ jobs:
     steps:
       - name: Checkout code
         uses: actions/checkout@v2
-
       - name: Validate branch name
         run: |
-          branch_name="${GITHUB_REF#refs/heads/}"
-          pattern="^(feature|release|hotfix)/[a-z0-9-]+$"
-          if [[ ! $branch_name =~ $pattern ]]; then
-            echo "ERROR: The name of the branch is not in the correct format!"
-            echo -e "Branch names should have a prefix
-          (feature/, release/, hotfix/) and should be in kebab-case."
-            echo "Example: feature/create-endpoint"
+          branch_name="${{ github.head_ref }}"
+          target_branch_name="${{ github.base_ref }}"
+          echo "branch: $branch_name to target branch: $target_branch_name"
+
+          release_pattern="^(release)/[0-9]+.[0-9]+$"
+          hotfix_pattern="^(hotfix)/[0-9]+.[0-9]+$"
+          feature_pattern="^(feature)/([a-zA-Z0-9-]+)$"
+
+          if [[ "$branch_name" =~ $feature_pattern ]]; then
+            echo "Feature branch detected"
+            if [[ "$target_branch_name" != "develop" ]]; then
+              echo "Feature branch must target develop"
+              exit 1
+            fi
+          elif [[ "$branch_name" =~ $release_pattern ]]; then
+            echo "Release branch detected"
+            if [[ "$target_branch_name" != "master" ]]; then
+              echo "Release branch must target master"
+              exit 1
+            fi
+          elif [[ "$branch_name" =~ $hotfix_pattern ]]; then
+            echo "Hotfix branch detected"
+            if [[ "$target_branch_name" != "master" ]]; then
+              echo "Hotfix branch must target master"
+              exit 1
+            fi
+          else
+            echo "Invalid branch name"
             exit 1
           fi
+        shell: bash
   test:
     runs-on: ubuntu-latest
     name: test
